[package]
name = "rust"
version = "0.1.0"
authors = ["Christian Scott <christian.s@canva.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "1.3.0"
